/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import javax.swing.JOptionPane;

/**
 *
 * @author enzoq
 */
public class frmNombres extends javax.swing.JFrame {

    /**
     * Creates new form frmNombres
     */
    public frmNombres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTam = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtTam = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxADatos = new javax.swing.JTextArea();
        btnMostrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnDefinir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        lblTitulo.setText("Control de Nombres");
        principal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 180, 30));

        lblTam.setText("Tamaño de arreglo");
        principal.add(lblTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lblNombre.setText("Nombre");
        principal.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamActionPerformed(evt);
            }
        });
        principal.add(txtTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 60, -1));
        principal.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        principal.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        TxADatos.setColumns(20);
        TxADatos.setRows(5);
        jScrollPane1.setViewportView(TxADatos);

        principal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        principal.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        principal.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        btnDefinir.setText("Definir");
        btnDefinir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefinirActionPerformed(evt);
            }
        });
        principal.add(btnDefinir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/imagen.jpeg"))); // NOI18N
        principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        getContentPane().add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                RutinasG.agregaNombre(txtNombre.getText()));
       txtNombre.setText("");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Gracias por usar el programa");
        System.exit(0);
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnDefinirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefinirActionPerformed
        // TODO add your handling code here:
       
        RutinasG.crearArreglo(Integer.parseInt(txtTam.getText()));
        JOptionPane.showMessageDialog(this, "Arreglo creado");
    }//GEN-LAST:event_btnDefinirActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        TxADatos.setText(RutinasG.mostrarArreglo());
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNombres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxADatos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDefinir;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTam;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel principal;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables
}
